version: '3'
services:
  ftp:
    image: fauria/vsftpd
    container_name: ftp_server
    restart: always
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_USER: "admin"
      FTP_PASS: "securepassword"
      PASV_ADDRESS: "localhost"
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      LOCAL_UMASK: "022"
      FILE_OPEN_MODE: "0666"
      LOCAL_ENABLE: "YES"
      WRITE_ENABLE: "YES"
    volumes:
      - ./data:/home/vsftpd/admin  # Changed this